site_name: æ•°æ®ç§‘å­¦ç ”ç©¶ç”Ÿ-è¿›é˜¶æŒ‡å—
repo_url: https://github.com/Messimeimei/personal-site  # ç”¨äºå±•ç¤ºgithubç›¸å…³ä¿¡æ¯
repo_name: ds-personal-site
copyright: Copyright @ 2025-present WhuMesiimeimei # ç‰ˆæƒå±•ç¤º

theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  # é¢œè‰²åˆ‡æ¢
  palette:
    - scheme: default         # â˜€ï¸ ç™½å¤©æ¨¡å¼
      primary: deep orange           # é¡¶æ è‰²ï¼šäº®è“ç§‘æŠ€æ„Ÿ
      accent: deep orange     # å¼ºè°ƒè‰²ï¼šè§å…‰ç»¿æŒ‰é’®ã€é“¾æ¥
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢è‡³å¤œæ™šæ¨¡å¼
    - scheme: slate           # ğŸŒ™ å¤œé—´æ¨¡å¼
      primary: cyan      # é¡¶æ è‰²ï¼šæ·±è“ç°ï¼Œæ²‰ç¨³ç§‘æŠ€æ„Ÿ
      accent: cyan            # å¼ºè°ƒè‰²ï¼šäº®ç»¿è‰²ï¼Œçªå‡ºæ˜¾ç¤º
      toggle:
        icon: material/weather-night
        name: åˆ‡æ¢è‡³ç™½å¤©æ¨¡å¼
  # ä¸€äº›äº¤äº’ç‰¹æ€§çš„è®¾ç½®
  features:
    - header.autohide
    - navigation.top
    - content.zoom  # âœ… å¯ç”¨ç¼©æ”¾åŠŸèƒ½

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - å‰è¨€: index.md
  - å¤šæ™ºèƒ½ä½“:
      - å¤šæ™ºèƒ½ä½“ä»‹ç»: multi-agent/start.md
  - MCP:
      - MCPåè®®ä»‹ç»: MCP/start.md
  - FastAPI:
      - FastAPIä»‹ç»: FastAPI/start.md
  - æœ¬åœ°æ¡Œé¢Agent:
      - ç›¸å…³èµ„æ–™: OS-Agent/materials.md
      - è®ºæ–‡è§£è¯»: OS-Agent/papers-interpretation.md
